// <auto-generated />
using System;
using System.Net;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PamyatRyadom.Api.Data;

#nullable disable

namespace PamyatRyadom.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260911181930_AdminUsersAuditEvents")]
    partial class AdminUsersAuditEvents
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PamyatRyadom.Api.Models.Auth.AuthIdentity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<string>("EmailNormalized")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("text")
                        .HasColumnName("email_normalized")
                        .HasComputedColumnSql("lower(email)", true);

                    b.Property<bool>("IsVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_verified");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("Phone")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("phone");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("provider");

                    b.Property<string>("ProviderUserId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("provider_user_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_auth_identities");

                    b.HasIndex("EmailNormalized")
                        .IsUnique()
                        .HasDatabaseName("ux_auth_identities_email_lower_when_email_provider")
                        .HasFilter("provider = 'email' AND email IS NOT NULL");

                    b.HasIndex("Phone")
                        .IsUnique()
                        .HasDatabaseName("ux_auth_identities_phone_when_phone_provider")
                        .HasFilter("provider = 'phone' AND phone IS NOT NULL");

                    b.HasIndex("Provider")
                        .HasDatabaseName("ix_auth_identities_provider");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_auth_identities_user_id");

                    b.HasIndex("Provider", "ProviderUserId")
                        .IsUnique()
                        .HasDatabaseName("ux_auth_identities_provider_provider_user_id")
                        .HasFilter("provider_user_id IS NOT NULL");

                    b.ToTable("auth_identities", null, t =>
                        {
                            t.HasCheckConstraint("ck_auth_identities_provider", "provider IN ('email', 'phone')");

                            t.HasCheckConstraint("ck_auth_identities_provider_contact", "(provider = 'email' AND email IS NOT NULL) OR (provider = 'phone' AND phone IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("PamyatRyadom.Api.Models.Auth.AuthSession", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<IPAddress>("IpAddress")
                        .HasColumnType("inet")
                        .HasColumnName("ip_address");

                    b.Property<bool>("IsPrivileged")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_privileged");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<DateTimeOffset?>("RotatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rotated_at");

                    b.Property<string>("SessionTokenHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("session_token_hash");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("user_agent");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_auth_sessions");

                    b.HasIndex("SessionTokenHash")
                        .IsUnique()
                        .HasDatabaseName("ux_auth_sessions_session_token_hash");

                    b.HasIndex("UserId", "RevokedAt", "ExpiresAt")
                        .HasDatabaseName("ix_auth_sessions_user_id_revoked_at_expires_at");

                    b.ToTable("auth_sessions", (string)null);
                });

            modelBuilder.Entity("PamyatRyadom.Api.Models.Auth.ConsentLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("AcceptedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("accepted_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("ConsentType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("consent_type");

                    b.Property<string>("DocumentVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("document_version");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<IPAddress>("IpAddress")
                        .IsRequired()
                        .HasColumnType("inet")
                        .HasColumnName("ip_address");

                    b.Property<string>("Phone")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("phone");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("user_agent");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_consent_logs");

                    b.HasIndex("Email")
                        .HasDatabaseName("ix_consent_logs_email_guest")
                        .HasFilter("user_id IS NULL");

                    b.HasIndex("UserId", "ConsentType", "AcceptedAt")
                        .HasDatabaseName("ix_consent_logs_user_id_consent_type_accepted_at");

                    b.ToTable("consent_logs", null, t =>
                        {
                            t.HasCheckConstraint("ck_consent_logs_type", "consent_type IN ('personal_data', 'marketing', 'cookies')");
                        });
                });

            modelBuilder.Entity("PamyatRyadom.Api.Models.Auth.LegalAcceptance", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("AcceptedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("accepted_at")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("DocumentId")
                        .HasColumnType("bigint")
                        .HasColumnName("document_id");

                    b.Property<IPAddress>("IpAddress")
                        .IsRequired()
                        .HasColumnType("inet")
                        .HasColumnName("ip_address");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("user_agent");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_legal_acceptances");

                    b.HasIndex("DocumentId")
                        .HasDatabaseName("ix_legal_acceptances_document_id");

                    b.HasIndex("UserId", "DocumentId")
                        .HasDatabaseName("ix_legal_acceptances_user_id_document_id");

                    b.ToTable("legal_acceptances", (string)null);
                });

            modelBuilder.Entity("PamyatRyadom.Api.Models.Auth.LegalDocument", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("content_hash");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset>("EffectiveAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_at");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("locale");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("draft")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_legal_documents");

                    b.HasIndex("Type", "Status")
                        .HasDatabaseName("ix_legal_documents_type_status");

                    b.HasIndex("Type", "Version", "Locale")
                        .IsUnique()
                        .HasDatabaseName("ux_legal_documents_type_version_locale");

                    b.ToTable("legal_documents", null, t =>
                        {
                            t.HasCheckConstraint("ck_legal_documents_status", "status IN ('draft', 'published', 'archived')");

                            t.HasCheckConstraint("ck_legal_documents_type", "type IN ('oferta_client', 'oferta_executor', 'privacy', 'cookies', 'refund_policy')");
                        });
                });

            modelBuilder.Entity("PamyatRyadom.Api.Models.Auth.MfaSecret", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset?>("EnabledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("enabled_at");

                    b.Property<JsonDocument>("RecoveryCodesHash")
                        .HasColumnType("jsonb")
                        .HasColumnName("recovery_codes_hash");

                    b.Property<string>("SecretEncrypted")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("secret_encrypted");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_mfa_secrets");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ux_mfa_secrets_user_id");

                    b.ToTable("mfa_secrets", (string)null);
                });

            modelBuilder.Entity("PamyatRyadom.Api.Models.Auth.OtpCode", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("AttemptCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("attempt_count");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("channel");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("code_hash");

                    b.Property<DateTimeOffset?>("ConsumedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consumed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("destination");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<IPAddress>("IpAddress")
                        .HasColumnType("inet")
                        .HasColumnName("ip_address");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("purpose");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("user_agent");

                    b.HasKey("Id")
                        .HasName("pk_otp_codes");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_otp_codes_expires_at");

                    b.HasIndex("Destination", "Purpose", "ConsumedAt")
                        .HasDatabaseName("ix_otp_codes_destination_purpose_consumed_at");

                    b.ToTable("otp_codes", null, t =>
                        {
                            t.HasCheckConstraint("ck_otp_codes_channel", "channel IN ('email', 'sms')");

                            t.HasCheckConstraint("ck_otp_codes_purpose", "purpose IN ('login', 'verify_email')");
                        });
                });

            modelBuilder.Entity("PamyatRyadom.Api.Models.Auth.SecurityAuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ActorRole")
                        .HasColumnType("text")
                        .HasColumnName("actor_role");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_type");

                    b.Property<IPAddress>("IpAddress")
                        .HasColumnType("inet")
                        .HasColumnName("ip_address");

                    b.Property<JsonDocument>("Metadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("user_agent");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_security_audit_logs");

                    b.HasIndex("EventType", "CreatedAt")
                        .HasDatabaseName("ix_security_audit_logs_event_type_created_at");

                    b.HasIndex("UserId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_security_audit_logs_user_id_created_at_desc");

                    b.ToTable("security_audit_logs", null, t =>
                        {
                            t.HasCheckConstraint("ck_security_audit_logs_actor_role", "actor_role IS NULL OR actor_role IN ('client', 'executor', 'dispatcher', 'qa', 'support', 'finance', 'admin', 'superadmin')");

                            t.HasCheckConstraint("ck_security_audit_logs_event_type", "event_type IN ('login_success', 'login_failed', 'logout', 'otp_requested', 'session_revoked', 'role_changed', 'mfa_enrolled', 'mfa_verified', 'catalog_changed', 'user_created', 'user_status_changed')");
                        });
                });

            modelBuilder.Entity("PamyatRyadom.Api.Models.Auth.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("display_name");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("Locale")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("locale");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("client")
                        .HasColumnName("role");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("active")
                        .HasColumnName("status");

                    b.Property<string>("Timezone")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("timezone");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Role")
                        .HasDatabaseName("ix_users_role");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_users_status");

                    b.ToTable("users", null, t =>
                        {
                            t.HasCheckConstraint("ck_users_role", "role IN ('client', 'executor', 'dispatcher', 'qa', 'support', 'finance', 'admin', 'superadmin')");

                            t.HasCheckConstraint("ck_users_status", "status IN ('active', 'blocked', 'deleted')");
                        });
                });

            modelBuilder.Entity("PamyatRyadom.Api.Models.BurialSites.BurialSite", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("BirthDateText")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("birth_date_text");

                    b.Property<long>("CemeteryId")
                        .HasColumnType("bigint")
                        .HasColumnName("cemetery_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DeathDateText")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("death_date_text");

                    b.Property<string>("DeceasedFullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("deceased_full_name");

                    b.Property<decimal?>("GeoLat")
                        .HasColumnType("numeric(9,7)")
                        .HasColumnName("geo_lat");

                    b.Property<decimal?>("GeoLng")
                        .HasColumnType("numeric(10,7)")
                        .HasColumnName("geo_lng");

                    b.Property<string>("Landmarks")
                        .HasColumnType("text")
                        .HasColumnName("landmarks");

                    b.Property<string>("LocationQuality")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("unverified")
                        .HasColumnName("location_quality");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<long>("OwnerUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("owner_user_id");

                    b.Property<string>("PlotSection")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("plot_section");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("active")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_burial_sites");

                    b.HasIndex("CemeteryId")
                        .HasDatabaseName("ix_burial_sites_cemetery_id");

                    b.HasIndex("OwnerUserId")
                        .HasDatabaseName("ix_burial_sites_owner_user_id");

                    b.HasIndex("OwnerUserId", "Status")
                        .HasDatabaseName("ix_burial_sites_owner_user_id_status");

                    b.ToTable("burial_sites", null, t =>
                        {
                            t.HasCheckConstraint("ck_burial_sites_location_quality", "location_quality IN ('unverified', 'sufficient', 'insufficient')");

                            t.HasCheckConstraint("ck_burial_sites_status", "status IN ('active', 'deleted')");
                        });
                });

            modelBuilder.Entity("PamyatRyadom.Api.Models.BurialSites.BurialSiteMember", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset?>("AcceptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("accepted_at");

                    b.Property<long>("BurialSiteId")
                        .HasColumnType("bigint")
                        .HasColumnName("burial_site_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset?>("InvitationExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("invitation_expires_at");

                    b.Property<string>("InvitationTokenHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("invitation_token_hash");

                    b.Property<long>("InvitedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("invited_by_user_id");

                    b.Property<string>("InvitedContact")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("invited_contact");

                    b.Property<string>("Permission")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("view")
                        .HasColumnName("permission");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_burial_site_members");

                    b.HasIndex("InvitationTokenHash")
                        .HasDatabaseName("ix_burial_site_members_invitation_token_hash");

                    b.HasIndex("InvitedByUserId")
                        .HasDatabaseName("ix_burial_site_members_invited_by_user_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_burial_site_members_user_id");

                    b.HasIndex("BurialSiteId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ux_burial_site_members_site_user_active")
                        .HasFilter("user_id IS NOT NULL AND revoked_at IS NULL");

                    b.ToTable("burial_site_members", null, t =>
                        {
                            t.HasCheckConstraint("ck_burial_site_members_permission", "permission IN ('view', 'order', 'manage')");

                            t.HasCheckConstraint("ck_burial_site_members_subject", "user_id IS NOT NULL OR invited_contact IS NOT NULL");
                        });
                });

            modelBuilder.Entity("PamyatRyadom.Api.Models.BurialSites.Cemetery", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("address");

                    b.Property<JsonDocument>("Contacts")
                        .HasColumnType("jsonb")
                        .HasColumnName("contacts");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<decimal?>("GeoLat")
                        .HasColumnType("numeric(9,7)")
                        .HasColumnName("geo_lat");

                    b.Property<decimal?>("GeoLng")
                        .HasColumnType("numeric(10,7)")
                        .HasColumnName("geo_lng");

                    b.Property<string>("Hours")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("hours");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("Region")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("region");

                    b.Property<string>("Rules")
                        .HasColumnType("text")
                        .HasColumnName("rules");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("active")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_cemeteries");

                    b.HasIndex("Region")
                        .HasDatabaseName("ix_cemeteries_region");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_cemeteries_status");

                    b.ToTable("cemeteries", null, t =>
                        {
                            t.HasCheckConstraint("ck_cemeteries_status", "status IN ('active', 'archived')");
                        });
                });

            modelBuilder.Entity("PamyatRyadom.Api.Models.Catalog.ChecklistTemplate", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<JsonDocument>("Items")
                        .HasColumnType("jsonb")
                        .HasColumnName("items");

                    b.Property<JsonDocument>("RequiredMedia")
                        .HasColumnType("jsonb")
                        .HasColumnName("required_media");

                    b.Property<long>("ServicePackageId")
                        .HasColumnType("bigint")
                        .HasColumnName("service_package_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_checklist_templates");

                    b.HasIndex("ServicePackageId")
                        .IsUnique()
                        .HasDatabaseName("ux_checklist_templates_package");

                    b.ToTable("checklist_templates", (string)null);
                });

            modelBuilder.Entity("PamyatRyadom.Api.Models.Catalog.ServicePackage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<JsonDocument>("Includes")
                        .HasColumnType("jsonb")
                        .HasColumnName("includes");

                    b.Property<JsonDocument>("Limits")
                        .HasColumnType("jsonb")
                        .HasColumnName("limits");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasDefaultValue("ru")
                        .HasColumnName("locale");

                    b.Property<decimal>("PriceFromRub")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("price_from_rub");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("draft")
                        .HasColumnName("status");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("version");

                    b.Property<string>("VisitsLabel")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("visits_label");

                    b.Property<int>("WarrantyDays")
                        .HasColumnType("integer")
                        .HasColumnName("warranty_days");

                    b.HasKey("Id")
                        .HasName("pk_service_packages");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_service_packages_status");

                    b.HasIndex("Code", "Version", "Locale")
                        .IsUnique()
                        .HasDatabaseName("ux_service_packages_code_version_locale");

                    b.ToTable("service_packages", null, t =>
                        {
                            t.HasCheckConstraint("ck_service_packages_price", "price_from_rub > 0");

                            t.HasCheckConstraint("ck_service_packages_published_at", "(status = 'published') = (published_at IS NOT NULL)");

                            t.HasCheckConstraint("ck_service_packages_status", "status IN ('draft', 'published', 'archived')");

                            t.HasCheckConstraint("ck_service_packages_warranty", "warranty_days >= 0");
                        });
                });

            modelBuilder.Entity("PamyatRyadom.Api.Models.Catalog.SubscriptionPlan", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasDefaultValue("ru")
                        .HasColumnName("locale");

                    b.Property<int>("PeriodMonths")
                        .HasColumnType("integer")
                        .HasColumnName("period_months");

                    b.Property<decimal>("PriceRub")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("price_rub");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<string>("ServicePackageCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("service_package_code");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("draft")
                        .HasColumnName("status");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("version");

                    b.Property<int>("VisitsTotal")
                        .HasColumnType("integer")
                        .HasColumnName("visits_total");

                    b.HasKey("Id")
                        .HasName("pk_subscription_plans");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_subscription_plans_status");

                    b.HasIndex("Code", "Version", "Locale")
                        .IsUnique()
                        .HasDatabaseName("ux_subscription_plans_code_version_locale");

                    b.ToTable("subscription_plans", null, t =>
                        {
                            t.HasCheckConstraint("ck_subscription_plans_period", "period_months > 0");

                            t.HasCheckConstraint("ck_subscription_plans_price", "price_rub > 0");

                            t.HasCheckConstraint("ck_subscription_plans_published_at", "(status = 'published') = (published_at IS NOT NULL)");

                            t.HasCheckConstraint("ck_subscription_plans_status", "status IN ('draft', 'published', 'archived')");

                            t.HasCheckConstraint("ck_subscription_plans_visits", "visits_total > 0");
                        });
                });

            modelBuilder.Entity("PamyatRyadom.Api.Models.Dispatch.Visit", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset?>("AcceptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("accepted_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DeclineReason")
                        .HasColumnType("text")
                        .HasColumnName("decline_reason");

                    b.Property<string>("ExecutorNote")
                        .HasColumnType("text")
                        .HasColumnName("executor_note");

                    b.Property<long?>("ExecutorUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("executor_user_id");

                    b.Property<DateTimeOffset?>("OfferExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("offer_expires_at");

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint")
                        .HasColumnName("order_id");

                    b.Property<decimal?>("PayoutRub")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("payout_rub");

                    b.Property<string>("ReviewNote")
                        .HasColumnType("text")
                        .HasColumnName("review_note");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at");

                    b.Property<long?>("ReviewedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("reviewed_by_user_id");

                    b.Property<DateTimeOffset?>("ScheduledFor")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_for");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("offered")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_visits");

                    b.HasIndex("ExecutorUserId", "Status")
                        .HasDatabaseName("ix_visits_executor_user_id_status");

                    b.HasIndex("OrderId", "Status")
                        .HasDatabaseName("ix_visits_order_id_status");

                    b.ToTable("visits", null, t =>
                        {
                            t.HasCheckConstraint("ck_visits_payout", "payout_rub IS NULL OR payout_rub >= 0");

                            t.HasCheckConstraint("ck_visits_status", "status IN ('offered', 'accepted', 'declined', 'in_progress', 'submitted', 'rework', 'approved', 'failed')");
                        });
                });

            modelBuilder.Entity("PamyatRyadom.Api.Models.Dispatch.VisitChecklistItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("key");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<bool>("Optional")
                        .HasColumnType("boolean")
                        .HasColumnName("optional");

                    b.Property<string>("Result")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("pending")
                        .HasColumnName("result");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("VisitId")
                        .HasColumnType("bigint")
                        .HasColumnName("visit_id");

                    b.HasKey("Id")
                        .HasName("pk_visit_checklist_items");

                    b.HasIndex("VisitId", "Key")
                        .IsUnique()
                        .HasDatabaseName("ux_visit_checklist_items_key");

                    b.ToTable("visit_checklist_items", null, t =>
                        {
                            t.HasCheckConstraint("ck_visit_checklist_items_note", "result NOT IN ('impossible', 'not_required') OR (note IS NOT NULL AND length(btrim(note)) > 0)");

                            t.HasCheckConstraint("ck_visit_checklist_items_result", "result IN ('pending', 'done', 'impossible', 'not_required')");
                        });
                });

            modelBuilder.Entity("PamyatRyadom.Api.Models.Media.MediaAsset", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ChecksumSha256")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("checksum_sha256");

                    b.Property<string>("ContentType")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("content_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<long?>("FileSizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size_bytes");

                    b.Property<int?>("Height")
                        .HasColumnType("integer")
                        .HasColumnName("height");

                    b.Property<string>("ModerationNote")
                        .HasColumnType("text")
                        .HasColumnName("moderation_note");

                    b.Property<long>("OwnerId")
                        .HasColumnType("bigint")
                        .HasColumnName("owner_id");

                    b.Property<string>("OwnerType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("owner_type");

                    b.Property<string>("Phase")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("reference")
                        .HasColumnName("phase");

                    b.Property<DateTimeOffset?>("ReadyAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ready_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("uploading")
                        .HasColumnName("status");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("storage_key");

                    b.Property<string>("ThumbnailKey")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("thumbnail_key");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<long?>("UploadedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("uploaded_by_user_id");

                    b.Property<int?>("Width")
                        .HasColumnType("integer")
                        .HasColumnName("width");

                    b.HasKey("Id")
                        .HasName("pk_media_assets");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_media_assets_status");

                    b.HasIndex("StorageKey")
                        .IsUnique()
                        .HasDatabaseName("ux_media_assets_storage_key");

                    b.HasIndex("UploadedByUserId")
                        .HasDatabaseName("ix_media_assets_uploaded_by_user_id");

                    b.HasIndex("OwnerType", "OwnerId", "Phase")
                        .HasDatabaseName("ix_media_assets_owner_type_owner_id_phase");

                    b.ToTable("media_assets", null, t =>
                        {
                            t.HasCheckConstraint("ck_media_assets_file_size", "file_size_bytes IS NULL OR file_size_bytes >= 0");

                            t.HasCheckConstraint("ck_media_assets_owner_type", "owner_type IN ('burial_site', 'order', 'visit', 'dispute')");

                            t.HasCheckConstraint("ck_media_assets_phase", "phase IN ('reference', 'before', 'process', 'after', 'document')");

                            t.HasCheckConstraint("ck_media_assets_ready_at", "(status = 'ready') = (ready_at IS NOT NULL)");

                            t.HasCheckConstraint("ck_media_assets_status", "status IN ('uploading', 'scanning', 'ready', 'quarantined', 'deleted')");
                        });
                });

            modelBuilder.Entity("PamyatRyadom.Api.Models.Orders.Estimate", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset?>("AcceptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("accepted_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint")
                        .HasColumnName("order_id");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<long?>("PublishedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("published_by_user_id");

                    b.Property<DateTimeOffset?>("RejectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rejected_at");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("text")
                        .HasColumnName("rejection_reason");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("draft")
                        .HasColumnName("status");

                    b.Property<decimal>("TotalRub")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("total_rub");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset?>("ValidUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_until");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_estimates");

                    b.HasIndex("OrderId")
                        .IsUnique()
                        .HasDatabaseName("ux_estimates_order_published")
                        .HasFilter("status = 'published'");

                    b.HasIndex("OrderId", "Version")
                        .IsUnique()
                        .HasDatabaseName("ux_estimates_order_version");

                    b.ToTable("estimates", null, t =>
                        {
                            t.HasCheckConstraint("ck_estimates_published_at", "status = 'draft' OR published_at IS NOT NULL");

                            t.HasCheckConstraint("ck_estimates_status", "status IN ('draft', 'published', 'accepted', 'rejected', 'superseded')");

                            t.HasCheckConstraint("ck_estimates_total", "total_rub >= 0");

                            t.HasCheckConstraint("ck_estimates_version", "version > 0");
                        });
                });

            modelBuilder.Entity("PamyatRyadom.Api.Models.Orders.EstimateLine", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("EstimateId")
                        .HasColumnType("bigint")
                        .HasColumnName("estimate_id");

                    b.Property<decimal>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(10,2)")
                        .HasDefaultValue(1m)
                        .HasColumnName("quantity");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<string>("Unit")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("unit");

                    b.Property<decimal>("UnitPriceRub")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("unit_price_rub");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_estimate_lines");

                    b.HasIndex("EstimateId", "SortOrder")
                        .HasDatabaseName("ix_estimate_lines_estimate_id_sort_order");

                    b.ToTable("estimate_lines", null, t =>
                        {
                            t.HasCheckConstraint("ck_estimate_lines_price_sign", "(type = 'discount' AND unit_price_rub <= 0) OR (type <> 'discount' AND unit_price_rub >= 0)");

                            t.HasCheckConstraint("ck_estimate_lines_quantity", "quantity > 0");

                            t.HasCheckConstraint("ck_estimate_lines_type", "type IN ('work', 'material', 'discount', 'delivery', 'extra')");
                        });
                });

            modelBuilder.Entity("PamyatRyadom.Api.Models.Orders.Order", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("BurialSiteId")
                        .HasColumnType("bigint")
                        .HasColumnName("burial_site_id");

                    b.Property<string>("CancellationReason")
                        .HasColumnType("text")
                        .HasColumnName("cancellation_reason");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("CustomerComment")
                        .HasColumnType("text")
                        .HasColumnName("customer_comment");

                    b.Property<long>("CustomerUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("customer_user_id");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("number");

                    b.Property<string>("PackageCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("package_code");

                    b.Property<decimal>("PackagePriceFromRub")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("package_price_from_rub");

                    b.Property<string>("PackageTitle")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("package_title");

                    b.Property<string>("PackageVersion")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("package_version");

                    b.Property<DateTimeOffset?>("PaidAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("paid_at");

                    b.Property<DateTimeOffset?>("PreferredFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("preferred_from");

                    b.Property<DateTimeOffset?>("PreferredTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("preferred_to");

                    b.Property<long>("ServicePackageId")
                        .HasColumnType("bigint")
                        .HasColumnName("service_package_id");

                    b.Property<string>("Source")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("source");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("draft")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("WarrantyDays")
                        .HasColumnType("integer")
                        .HasColumnName("warranty_days");

                    b.HasKey("Id")
                        .HasName("pk_orders");

                    b.HasIndex("BurialSiteId")
                        .HasDatabaseName("ix_orders_burial_site_id");

                    b.HasIndex("Number")
                        .IsUnique()
                        .HasDatabaseName("ux_orders_number");

                    b.HasIndex("ServicePackageId")
                        .HasDatabaseName("ix_orders_service_package_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_orders_status");

                    b.HasIndex("CustomerUserId", "Status")
                        .HasDatabaseName("ix_orders_customer_user_id_status");

                    b.ToTable("orders", null, t =>
                        {
                            t.HasCheckConstraint("ck_orders_package_price", "package_price_from_rub > 0");

                            t.HasCheckConstraint("ck_orders_status", "status IN ('draft', 'submitted', 'location_review', 'estimate_ready', 'awaiting_payment', 'paid', 'assigning', 'assigned', 'in_progress', 'extra_approval', 'qa_review', 'customer_review', 'completed', 'disputed', 'cancelled', 'refunded')");

                            t.HasCheckConstraint("ck_orders_warranty", "warranty_days >= 0");

                            t.HasCheckConstraint("ck_orders_window", "preferred_from IS NULL OR preferred_to IS NULL OR preferred_from <= preferred_to");
                        });
                });

            modelBuilder.Entity("PamyatRyadom.Api.Models.Orders.OrderStatusHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ActorRole")
                        .HasColumnType("text")
                        .HasColumnName("actor_role");

                    b.Property<long?>("ActorUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("actor_user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("FromStatus")
                        .HasColumnType("text")
                        .HasColumnName("from_status");

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint")
                        .HasColumnName("order_id");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<string>("ToStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("to_status");

                    b.HasKey("Id")
                        .HasName("pk_order_status_history");

                    b.HasIndex("OrderId", "CreatedAt")
                        .HasDatabaseName("ix_order_status_history_order_id_created_at");

                    b.ToTable("order_status_history", null, t =>
                        {
                            t.HasCheckConstraint("ck_order_status_history_from", "from_status IS NULL OR from_status IN ('draft', 'submitted', 'location_review', 'estimate_ready', 'awaiting_payment', 'paid', 'assigning', 'assigned', 'in_progress', 'extra_approval', 'qa_review', 'customer_review', 'completed', 'disputed', 'cancelled', 'refunded')");

                            t.HasCheckConstraint("ck_order_status_history_to", "to_status IN ('draft', 'submitted', 'location_review', 'estimate_ready', 'awaiting_payment', 'paid', 'assigning', 'assigned', 'in_progress', 'extra_approval', 'qa_review', 'customer_review', 'completed', 'disputed', 'cancelled', 'refunded')");
                        });
                });

            modelBuilder.Entity("PamyatRyadom.Api.Models.Payments.Payment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("AmountRub")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("amount_rub");

                    b.Property<string>("ConfirmationUrl")
                        .HasColumnType("text")
                        .HasColumnName("confirmation_url");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("EstimateVersion")
                        .HasColumnType("integer")
                        .HasColumnName("estimate_version");

                    b.Property<string>("FailureReason")
                        .HasColumnType("text")
                        .HasColumnName("failure_reason");

                    b.Property<string>("IdempotenceKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("idempotence_key");

                    b.Property<DateTimeOffset?>("LastCheckedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_checked_at");

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint")
                        .HasColumnName("order_id");

                    b.Property<string>("OrderRef")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("order_ref");

                    b.Property<DateTimeOffset?>("PaidAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("paid_at");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("provider");

                    b.Property<string>("ProviderPaymentId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("provider_payment_id");

                    b.Property<DateTimeOffset?>("RefundedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("refunded_at");

                    b.Property<decimal>("RefundedRub")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(12,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("refunded_rub");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("pending")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_payments");

                    b.HasIndex("OrderRef")
                        .IsUnique()
                        .HasDatabaseName("ux_payments_order_ref");

                    b.HasIndex("ProviderPaymentId")
                        .IsUnique()
                        .HasDatabaseName("ux_payments_provider_payment_id")
                        .HasFilter("provider_payment_id IS NOT NULL");

                    b.HasIndex("OrderId", "Status")
                        .HasDatabaseName("ix_payments_order_id_status");

                    b.ToTable("payments", null, t =>
                        {
                            t.HasCheckConstraint("ck_payments_amount", "amount_rub > 0");

                            t.HasCheckConstraint("ck_payments_refunded", "refunded_rub >= 0 AND refunded_rub <= amount_rub");

                            t.HasCheckConstraint("ck_payments_status", "status IN ('pending', 'waiting_for_capture', 'succeeded', 'canceled', 'failed', 'refunded')");
                        });
                });

            modelBuilder.Entity("PamyatRyadom.Api.Models.Auth.AuthIdentity", b =>
                {
                    b.HasOne("PamyatRyadom.Api.Models.Auth.User", "User")
                        .WithMany("AuthIdentities")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_auth_identities_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PamyatRyadom.Api.Models.Auth.AuthSession", b =>
                {
                    b.HasOne("PamyatRyadom.Api.Models.Auth.User", "User")
                        .WithMany("AuthSessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_auth_sessions_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PamyatRyadom.Api.Models.Auth.ConsentLog", b =>
                {
                    b.HasOne("PamyatRyadom.Api.Models.Auth.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_consent_logs_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PamyatRyadom.Api.Models.Auth.LegalAcceptance", b =>
                {
                    b.HasOne("PamyatRyadom.Api.Models.Auth.LegalDocument", "Document")
                        .WithMany("Acceptances")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_legal_acceptances_legal_documents_document_id");

                    b.HasOne("PamyatRyadom.Api.Models.Auth.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_legal_acceptances_users_user_id");

                    b.Navigation("Document");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PamyatRyadom.Api.Models.Auth.MfaSecret", b =>
                {
                    b.HasOne("PamyatRyadom.Api.Models.Auth.User", "User")
                        .WithOne("MfaSecret")
                        .HasForeignKey("PamyatRyadom.Api.Models.Auth.MfaSecret", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_mfa_secrets_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PamyatRyadom.Api.Models.Auth.SecurityAuditLog", b =>
                {
                    b.HasOne("PamyatRyadom.Api.Models.Auth.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_security_audit_logs_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PamyatRyadom.Api.Models.BurialSites.BurialSite", b =>
                {
                    b.HasOne("PamyatRyadom.Api.Models.BurialSites.Cemetery", "Cemetery")
                        .WithMany("BurialSites")
                        .HasForeignKey("CemeteryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_burial_sites_cemeteries_cemetery_id");

                    b.HasOne("PamyatRyadom.Api.Models.Auth.User", null)
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_burial_sites_users_owner_user_id");

                    b.Navigation("Cemetery");
                });

            modelBuilder.Entity("PamyatRyadom.Api.Models.BurialSites.BurialSiteMember", b =>
                {
                    b.HasOne("PamyatRyadom.Api.Models.BurialSites.BurialSite", "BurialSite")
                        .WithMany("Members")
                        .HasForeignKey("BurialSiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_burial_site_members_burial_sites_burial_site_id");

                    b.HasOne("PamyatRyadom.Api.Models.Auth.User", null)
                        .WithMany()
                        .HasForeignKey("InvitedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_burial_site_members_users_invited_by_user_id");

                    b.HasOne("PamyatRyadom.Api.Models.Auth.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_burial_site_members_users_user_id");

                    b.Navigation("BurialSite");
                });

            modelBuilder.Entity("PamyatRyadom.Api.Models.Catalog.ChecklistTemplate", b =>
                {
                    b.HasOne("PamyatRyadom.Api.Models.Catalog.ServicePackage", "ServicePackage")
                        .WithOne("ChecklistTemplate")
                        .HasForeignKey("PamyatRyadom.Api.Models.Catalog.ChecklistTemplate", "ServicePackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_checklist_templates_service_packages_service_package_id");

                    b.Navigation("ServicePackage");
                });

            modelBuilder.Entity("PamyatRyadom.Api.Models.Dispatch.Visit", b =>
                {
                    b.HasOne("PamyatRyadom.Api.Models.Auth.User", null)
                        .WithMany()
                        .HasForeignKey("ExecutorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_visits_users_executor_user_id");

                    b.HasOne("PamyatRyadom.Api.Models.Orders.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_visits_orders_order_id");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("PamyatRyadom.Api.Models.Dispatch.VisitChecklistItem", b =>
                {
                    b.HasOne("PamyatRyadom.Api.Models.Dispatch.Visit", "Visit")
                        .WithMany("ChecklistItems")
                        .HasForeignKey("VisitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_visit_checklist_items_visits_visit_id");

                    b.Navigation("Visit");
                });

            modelBuilder.Entity("PamyatRyadom.Api.Models.Media.MediaAsset", b =>
                {
                    b.HasOne("PamyatRyadom.Api.Models.Auth.User", null)
                        .WithMany()
                        .HasForeignKey("UploadedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_media_assets_users_uploaded_by_user_id");
                });

            modelBuilder.Entity("PamyatRyadom.Api.Models.Orders.Estimate", b =>
                {
                    b.HasOne("PamyatRyadom.Api.Models.Orders.Order", "Order")
                        .WithMany("Estimates")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_estimates_orders_order_id");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("PamyatRyadom.Api.Models.Orders.EstimateLine", b =>
                {
                    b.HasOne("PamyatRyadom.Api.Models.Orders.Estimate", "Estimate")
                        .WithMany("Lines")
                        .HasForeignKey("EstimateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_estimate_lines_estimates_estimate_id");

                    b.Navigation("Estimate");
                });

            modelBuilder.Entity("PamyatRyadom.Api.Models.Orders.Order", b =>
                {
                    b.HasOne("PamyatRyadom.Api.Models.BurialSites.BurialSite", "BurialSite")
                        .WithMany()
                        .HasForeignKey("BurialSiteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_orders_burial_sites_burial_site_id");

                    b.HasOne("PamyatRyadom.Api.Models.Auth.User", null)
                        .WithMany()
                        .HasForeignKey("CustomerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_orders_users_customer_user_id");

                    b.HasOne("PamyatRyadom.Api.Models.Catalog.ServicePackage", null)
                        .WithMany()
                        .HasForeignKey("ServicePackageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_orders_service_packages_service_package_id");

                    b.Navigation("BurialSite");
                });

            modelBuilder.Entity("PamyatRyadom.Api.Models.Orders.OrderStatusHistory", b =>
                {
                    b.HasOne("PamyatRyadom.Api.Models.Orders.Order", "Order")
                        .WithMany("StatusHistory")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_order_status_history_orders_order_id");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("PamyatRyadom.Api.Models.Payments.Payment", b =>
                {
                    b.HasOne("PamyatRyadom.Api.Models.Orders.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_payments_orders_order_id");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("PamyatRyadom.Api.Models.Auth.LegalDocument", b =>
                {
                    b.Navigation("Acceptances");
                });

            modelBuilder.Entity("PamyatRyadom.Api.Models.Auth.User", b =>
                {
                    b.Navigation("AuthIdentities");

                    b.Navigation("AuthSessions");

                    b.Navigation("MfaSecret");
                });

            modelBuilder.Entity("PamyatRyadom.Api.Models.BurialSites.BurialSite", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("PamyatRyadom.Api.Models.BurialSites.Cemetery", b =>
                {
                    b.Navigation("BurialSites");
                });

            modelBuilder.Entity("PamyatRyadom.Api.Models.Catalog.ServicePackage", b =>
                {
                    b.Navigation("ChecklistTemplate");
                });

            modelBuilder.Entity("PamyatRyadom.Api.Models.Dispatch.Visit", b =>
                {
                    b.Navigation("ChecklistItems");
                });

            modelBuilder.Entity("PamyatRyadom.Api.Models.Orders.Estimate", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("PamyatRyadom.Api.Models.Orders.Order", b =>
                {
                    b.Navigation("Estimates");

                    b.Navigation("StatusHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
