// <auto-generated />
using System;
using System.Net;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PamyatRyadom.Api.Data;

#nullable disable

namespace PamyatRyadom.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260825055436_BurialSitesAndMedia")]
    partial class BurialSitesAndMedia
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PamyatRyadom.Api.Models.Auth.AuthIdentity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<string>("EmailNormalized")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("text")
                        .HasColumnName("email_normalized")
                        .HasComputedColumnSql("lower(email)", true);

                    b.Property<bool>("IsVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_verified");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("Phone")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("phone");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("provider");

                    b.Property<string>("ProviderUserId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("provider_user_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_auth_identities");

                    b.HasIndex("EmailNormalized")
                        .IsUnique()
                        .HasDatabaseName("ux_auth_identities_email_lower_when_email_provider")
                        .HasFilter("provider = 'email' AND email IS NOT NULL");

                    b.HasIndex("Phone")
                        .IsUnique()
                        .HasDatabaseName("ux_auth_identities_phone_when_phone_provider")
                        .HasFilter("provider = 'phone' AND phone IS NOT NULL");

                    b.HasIndex("Provider")
                        .HasDatabaseName("ix_auth_identities_provider");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_auth_identities_user_id");

                    b.HasIndex("Provider", "ProviderUserId")
                        .IsUnique()
                        .HasDatabaseName("ux_auth_identities_provider_provider_user_id")
                        .HasFilter("provider_user_id IS NOT NULL");

                    b.ToTable("auth_identities", null, t =>
                        {
                            t.HasCheckConstraint("ck_auth_identities_provider", "provider IN ('email', 'phone')");

                            t.HasCheckConstraint("ck_auth_identities_provider_contact", "(provider = 'email' AND email IS NOT NULL) OR (provider = 'phone' AND phone IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("PamyatRyadom.Api.Models.Auth.AuthSession", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<IPAddress>("IpAddress")
                        .HasColumnType("inet")
                        .HasColumnName("ip_address");

                    b.Property<bool>("IsPrivileged")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_privileged");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<DateTimeOffset?>("RotatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rotated_at");

                    b.Property<string>("SessionTokenHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("session_token_hash");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("user_agent");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_auth_sessions");

                    b.HasIndex("SessionTokenHash")
                        .IsUnique()
                        .HasDatabaseName("ux_auth_sessions_session_token_hash");

                    b.HasIndex("UserId", "RevokedAt", "ExpiresAt")
                        .HasDatabaseName("ix_auth_sessions_user_id_revoked_at_expires_at");

                    b.ToTable("auth_sessions", (string)null);
                });

            modelBuilder.Entity("PamyatRyadom.Api.Models.Auth.ConsentLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("AcceptedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("accepted_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("ConsentType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("consent_type");

                    b.Property<string>("DocumentVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("document_version");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<IPAddress>("IpAddress")
                        .IsRequired()
                        .HasColumnType("inet")
                        .HasColumnName("ip_address");

                    b.Property<string>("Phone")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("phone");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("user_agent");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_consent_logs");

                    b.HasIndex("Email")
                        .HasDatabaseName("ix_consent_logs_email_guest")
                        .HasFilter("user_id IS NULL");

                    b.HasIndex("UserId", "ConsentType", "AcceptedAt")
                        .HasDatabaseName("ix_consent_logs_user_id_consent_type_accepted_at");

                    b.ToTable("consent_logs", null, t =>
                        {
                            t.HasCheckConstraint("ck_consent_logs_type", "consent_type IN ('personal_data', 'marketing', 'cookies')");
                        });
                });

            modelBuilder.Entity("PamyatRyadom.Api.Models.Auth.LegalAcceptance", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("AcceptedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("accepted_at")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("DocumentId")
                        .HasColumnType("bigint")
                        .HasColumnName("document_id");

                    b.Property<IPAddress>("IpAddress")
                        .IsRequired()
                        .HasColumnType("inet")
                        .HasColumnName("ip_address");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("user_agent");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_legal_acceptances");

                    b.HasIndex("DocumentId")
                        .HasDatabaseName("ix_legal_acceptances_document_id");

                    b.HasIndex("UserId", "DocumentId")
                        .HasDatabaseName("ix_legal_acceptances_user_id_document_id");

                    b.ToTable("legal_acceptances", (string)null);
                });

            modelBuilder.Entity("PamyatRyadom.Api.Models.Auth.LegalDocument", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("content_hash");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset>("EffectiveAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_at");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("locale");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("draft")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_legal_documents");

                    b.HasIndex("Type", "Status")
                        .HasDatabaseName("ix_legal_documents_type_status");

                    b.HasIndex("Type", "Version", "Locale")
                        .IsUnique()
                        .HasDatabaseName("ux_legal_documents_type_version_locale");

                    b.ToTable("legal_documents", null, t =>
                        {
                            t.HasCheckConstraint("ck_legal_documents_status", "status IN ('draft', 'published', 'archived')");

                            t.HasCheckConstraint("ck_legal_documents_type", "type IN ('oferta_client', 'oferta_executor', 'privacy', 'cookies', 'refund_policy')");
                        });
                });

            modelBuilder.Entity("PamyatRyadom.Api.Models.Auth.MfaSecret", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset?>("EnabledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("enabled_at");

                    b.Property<JsonDocument>("RecoveryCodesHash")
                        .HasColumnType("jsonb")
                        .HasColumnName("recovery_codes_hash");

                    b.Property<string>("SecretEncrypted")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("secret_encrypted");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_mfa_secrets");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ux_mfa_secrets_user_id");

                    b.ToTable("mfa_secrets", (string)null);
                });

            modelBuilder.Entity("PamyatRyadom.Api.Models.Auth.OtpCode", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("AttemptCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("attempt_count");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("channel");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("code_hash");

                    b.Property<DateTimeOffset?>("ConsumedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consumed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("destination");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<IPAddress>("IpAddress")
                        .HasColumnType("inet")
                        .HasColumnName("ip_address");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("purpose");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("user_agent");

                    b.HasKey("Id")
                        .HasName("pk_otp_codes");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_otp_codes_expires_at");

                    b.HasIndex("Destination", "Purpose", "ConsumedAt")
                        .HasDatabaseName("ix_otp_codes_destination_purpose_consumed_at");

                    b.ToTable("otp_codes", null, t =>
                        {
                            t.HasCheckConstraint("ck_otp_codes_channel", "channel IN ('email', 'sms')");

                            t.HasCheckConstraint("ck_otp_codes_purpose", "purpose IN ('login', 'verify_email')");
                        });
                });

            modelBuilder.Entity("PamyatRyadom.Api.Models.Auth.SecurityAuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ActorRole")
                        .HasColumnType("text")
                        .HasColumnName("actor_role");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_type");

                    b.Property<IPAddress>("IpAddress")
                        .HasColumnType("inet")
                        .HasColumnName("ip_address");

                    b.Property<JsonDocument>("Metadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("user_agent");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_security_audit_logs");

                    b.HasIndex("EventType", "CreatedAt")
                        .HasDatabaseName("ix_security_audit_logs_event_type_created_at");

                    b.HasIndex("UserId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_security_audit_logs_user_id_created_at_desc");

                    b.ToTable("security_audit_logs", null, t =>
                        {
                            t.HasCheckConstraint("ck_security_audit_logs_actor_role", "actor_role IS NULL OR actor_role IN ('client', 'executor', 'dispatcher', 'qa', 'support', 'finance', 'admin', 'superadmin')");

                            t.HasCheckConstraint("ck_security_audit_logs_event_type", "event_type IN ('login_success', 'login_failed', 'logout', 'otp_requested', 'session_revoked', 'role_changed', 'mfa_enrolled', 'mfa_verified')");
                        });
                });

            modelBuilder.Entity("PamyatRyadom.Api.Models.Auth.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("display_name");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("Locale")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("locale");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("client")
                        .HasColumnName("role");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("active")
                        .HasColumnName("status");

                    b.Property<string>("Timezone")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("timezone");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Role")
                        .HasDatabaseName("ix_users_role");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_users_status");

                    b.ToTable("users", null, t =>
                        {
                            t.HasCheckConstraint("ck_users_role", "role IN ('client', 'executor', 'dispatcher', 'qa', 'support', 'finance', 'admin', 'superadmin')");

                            t.HasCheckConstraint("ck_users_status", "status IN ('active', 'blocked', 'deleted')");
                        });
                });

            modelBuilder.Entity("PamyatRyadom.Api.Models.BurialSites.BurialSite", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("BirthDateText")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("birth_date_text");

                    b.Property<long>("CemeteryId")
                        .HasColumnType("bigint")
                        .HasColumnName("cemetery_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DeathDateText")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("death_date_text");

                    b.Property<string>("DeceasedFullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("deceased_full_name");

                    b.Property<decimal?>("GeoLat")
                        .HasColumnType("numeric(9,7)")
                        .HasColumnName("geo_lat");

                    b.Property<decimal?>("GeoLng")
                        .HasColumnType("numeric(10,7)")
                        .HasColumnName("geo_lng");

                    b.Property<string>("Landmarks")
                        .HasColumnType("text")
                        .HasColumnName("landmarks");

                    b.Property<string>("LocationQuality")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("unverified")
                        .HasColumnName("location_quality");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<long>("OwnerUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("owner_user_id");

                    b.Property<string>("PlotSection")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("plot_section");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("active")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_burial_sites");

                    b.HasIndex("CemeteryId")
                        .HasDatabaseName("ix_burial_sites_cemetery_id");

                    b.HasIndex("OwnerUserId")
                        .HasDatabaseName("ix_burial_sites_owner_user_id");

                    b.HasIndex("OwnerUserId", "Status")
                        .HasDatabaseName("ix_burial_sites_owner_user_id_status");

                    b.ToTable("burial_sites", null, t =>
                        {
                            t.HasCheckConstraint("ck_burial_sites_location_quality", "location_quality IN ('unverified', 'sufficient', 'insufficient')");

                            t.HasCheckConstraint("ck_burial_sites_status", "status IN ('active', 'deleted')");
                        });
                });

            modelBuilder.Entity("PamyatRyadom.Api.Models.BurialSites.BurialSiteMember", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset?>("AcceptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("accepted_at");

                    b.Property<long>("BurialSiteId")
                        .HasColumnType("bigint")
                        .HasColumnName("burial_site_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset?>("InvitationExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("invitation_expires_at");

                    b.Property<string>("InvitationTokenHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("invitation_token_hash");

                    b.Property<long>("InvitedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("invited_by_user_id");

                    b.Property<string>("InvitedContact")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("invited_contact");

                    b.Property<string>("Permission")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("view")
                        .HasColumnName("permission");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_burial_site_members");

                    b.HasIndex("InvitationTokenHash")
                        .HasDatabaseName("ix_burial_site_members_invitation_token_hash");

                    b.HasIndex("InvitedByUserId")
                        .HasDatabaseName("ix_burial_site_members_invited_by_user_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_burial_site_members_user_id");

                    b.HasIndex("BurialSiteId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ux_burial_site_members_site_user_active")
                        .HasFilter("user_id IS NOT NULL AND revoked_at IS NULL");

                    b.ToTable("burial_site_members", null, t =>
                        {
                            t.HasCheckConstraint("ck_burial_site_members_permission", "permission IN ('view', 'order', 'manage')");

                            t.HasCheckConstraint("ck_burial_site_members_subject", "user_id IS NOT NULL OR invited_contact IS NOT NULL");
                        });
                });

            modelBuilder.Entity("PamyatRyadom.Api.Models.BurialSites.Cemetery", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("address");

                    b.Property<JsonDocument>("Contacts")
                        .HasColumnType("jsonb")
                        .HasColumnName("contacts");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<decimal?>("GeoLat")
                        .HasColumnType("numeric(9,7)")
                        .HasColumnName("geo_lat");

                    b.Property<decimal?>("GeoLng")
                        .HasColumnType("numeric(10,7)")
                        .HasColumnName("geo_lng");

                    b.Property<string>("Hours")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("hours");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("Region")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("region");

                    b.Property<string>("Rules")
                        .HasColumnType("text")
                        .HasColumnName("rules");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("active")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_cemeteries");

                    b.HasIndex("Region")
                        .HasDatabaseName("ix_cemeteries_region");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_cemeteries_status");

                    b.ToTable("cemeteries", null, t =>
                        {
                            t.HasCheckConstraint("ck_cemeteries_status", "status IN ('active', 'archived')");
                        });
                });

            modelBuilder.Entity("PamyatRyadom.Api.Models.Media.MediaAsset", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ChecksumSha256")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("checksum_sha256");

                    b.Property<string>("ContentType")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("content_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<long?>("FileSizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size_bytes");

                    b.Property<int?>("Height")
                        .HasColumnType("integer")
                        .HasColumnName("height");

                    b.Property<string>("ModerationNote")
                        .HasColumnType("text")
                        .HasColumnName("moderation_note");

                    b.Property<long>("OwnerId")
                        .HasColumnType("bigint")
                        .HasColumnName("owner_id");

                    b.Property<string>("OwnerType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("owner_type");

                    b.Property<string>("Phase")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("reference")
                        .HasColumnName("phase");

                    b.Property<DateTimeOffset?>("ReadyAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ready_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("uploading")
                        .HasColumnName("status");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("storage_key");

                    b.Property<string>("ThumbnailKey")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("thumbnail_key");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<long?>("UploadedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("uploaded_by_user_id");

                    b.Property<int?>("Width")
                        .HasColumnType("integer")
                        .HasColumnName("width");

                    b.HasKey("Id")
                        .HasName("pk_media_assets");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_media_assets_status");

                    b.HasIndex("StorageKey")
                        .IsUnique()
                        .HasDatabaseName("ux_media_assets_storage_key");

                    b.HasIndex("UploadedByUserId")
                        .HasDatabaseName("ix_media_assets_uploaded_by_user_id");

                    b.HasIndex("OwnerType", "OwnerId", "Phase")
                        .HasDatabaseName("ix_media_assets_owner_type_owner_id_phase");

                    b.ToTable("media_assets", null, t =>
                        {
                            t.HasCheckConstraint("ck_media_assets_file_size", "file_size_bytes IS NULL OR file_size_bytes >= 0");

                            t.HasCheckConstraint("ck_media_assets_owner_type", "owner_type IN ('burial_site', 'order', 'visit', 'dispute')");

                            t.HasCheckConstraint("ck_media_assets_phase", "phase IN ('reference', 'before', 'process', 'after', 'document')");

                            t.HasCheckConstraint("ck_media_assets_ready_at", "(status = 'ready') = (ready_at IS NOT NULL)");

                            t.HasCheckConstraint("ck_media_assets_status", "status IN ('uploading', 'scanning', 'ready', 'quarantined', 'deleted')");
                        });
                });

            modelBuilder.Entity("PamyatRyadom.Api.Models.Auth.AuthIdentity", b =>
                {
                    b.HasOne("PamyatRyadom.Api.Models.Auth.User", "User")
                        .WithMany("AuthIdentities")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_auth_identities_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PamyatRyadom.Api.Models.Auth.AuthSession", b =>
                {
                    b.HasOne("PamyatRyadom.Api.Models.Auth.User", "User")
                        .WithMany("AuthSessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_auth_sessions_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PamyatRyadom.Api.Models.Auth.ConsentLog", b =>
                {
                    b.HasOne("PamyatRyadom.Api.Models.Auth.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_consent_logs_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PamyatRyadom.Api.Models.Auth.LegalAcceptance", b =>
                {
                    b.HasOne("PamyatRyadom.Api.Models.Auth.LegalDocument", "Document")
                        .WithMany("Acceptances")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_legal_acceptances_legal_documents_document_id");

                    b.HasOne("PamyatRyadom.Api.Models.Auth.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_legal_acceptances_users_user_id");

                    b.Navigation("Document");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PamyatRyadom.Api.Models.Auth.MfaSecret", b =>
                {
                    b.HasOne("PamyatRyadom.Api.Models.Auth.User", "User")
                        .WithOne("MfaSecret")
                        .HasForeignKey("PamyatRyadom.Api.Models.Auth.MfaSecret", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_mfa_secrets_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PamyatRyadom.Api.Models.Auth.SecurityAuditLog", b =>
                {
                    b.HasOne("PamyatRyadom.Api.Models.Auth.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_security_audit_logs_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PamyatRyadom.Api.Models.BurialSites.BurialSite", b =>
                {
                    b.HasOne("PamyatRyadom.Api.Models.BurialSites.Cemetery", "Cemetery")
                        .WithMany("BurialSites")
                        .HasForeignKey("CemeteryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_burial_sites_cemeteries_cemetery_id");

                    b.HasOne("PamyatRyadom.Api.Models.Auth.User", null)
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_burial_sites_users_owner_user_id");

                    b.Navigation("Cemetery");
                });

            modelBuilder.Entity("PamyatRyadom.Api.Models.BurialSites.BurialSiteMember", b =>
                {
                    b.HasOne("PamyatRyadom.Api.Models.BurialSites.BurialSite", "BurialSite")
                        .WithMany("Members")
                        .HasForeignKey("BurialSiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_burial_site_members_burial_sites_burial_site_id");

                    b.HasOne("PamyatRyadom.Api.Models.Auth.User", null)
                        .WithMany()
                        .HasForeignKey("InvitedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_burial_site_members_users_invited_by_user_id");

                    b.HasOne("PamyatRyadom.Api.Models.Auth.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_burial_site_members_users_user_id");

                    b.Navigation("BurialSite");
                });

            modelBuilder.Entity("PamyatRyadom.Api.Models.Media.MediaAsset", b =>
                {
                    b.HasOne("PamyatRyadom.Api.Models.Auth.User", null)
                        .WithMany()
                        .HasForeignKey("UploadedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_media_assets_users_uploaded_by_user_id");
                });

            modelBuilder.Entity("PamyatRyadom.Api.Models.Auth.LegalDocument", b =>
                {
                    b.Navigation("Acceptances");
                });

            modelBuilder.Entity("PamyatRyadom.Api.Models.Auth.User", b =>
                {
                    b.Navigation("AuthIdentities");

                    b.Navigation("AuthSessions");

                    b.Navigation("MfaSecret");
                });

            modelBuilder.Entity("PamyatRyadom.Api.Models.BurialSites.BurialSite", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("PamyatRyadom.Api.Models.BurialSites.Cemetery", b =>
                {
                    b.Navigation("BurialSites");
                });
#pragma warning restore 612, 618
        }
    }
}
